# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# 参考：https://circleci.com/developer/ja/orbs/orb/circleci/aws-cli
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.2.0
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.3.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  cfn-lint:
    # テンプレートの構文や構成チェックを行う自動Lint処理
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  execute-cloudformation:
    # orbs使う時はexecutorとする
    executor: aws-cli/default
    steps:
      # Checkout the code as the first step.
      - checkout
      # https://circleci.com/developer/ja/orbs/orb/circleci/aws-cli のsetupを使う
      - aws-cli/setup:
          # 下記の環境変数はcircleci実行時に設定する
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to aws from template
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/cfn_network.yml \
              --stack-name raisetech-aws-lecture13-ci-network
            aws cloudformation deploy --template-file cloudformation/cfn_iam_role.yml \
              --stack-name raisetech-aws-lecture13-ci-iam-role --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/cfn_application.yml \
              --stack-name raisetech-aws-lecture13-ci-application --capabilities CAPABILITY_NAMED_IAM

  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:MfFRPirALrmTRAdw/j+bF6ghu9kvK3WI2JdrdMSSOlo"
      - ansible-playbook/install:
          version: 2.10.7
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      # EC2 の Public IP を取得し、Ansible 用 inventory を動的に作成
      - run:
          name: Get public IP of target node
          command: |
            TARGET_IP=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=aws-lecture13-ci-ec2" \
              --query "Reservations[*].Instances[*].PublicIpAddress" \
              --output text)
            echo -e "[target_node]\n${TARGET_IP} ansible_user=ec2-user \
            ansible_ssh_private_key_file=~/.ssh/id_rsa_aws_from_m1_win.pem" > ansible/inventory
            cat ansible/inventory
            echo "${TARGET_IP}" > target_ip.txt
      - run:
          name: Get S3 Bucket name from CloudFormation
          command: |
            AWS_S3_BUCKET_NAME=$(aws cloudformation describe-stacks \
              --stack-name raisetech-aws-lecture13-ci-application \
              --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" \
              --output text)
            echo "export AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}" >> $BASH_ENV
      # RDS パスワードを Secrets Manager から取得し、環境変数にセット
      - run:
          name: Get RDS password from AWS Secrets Manager
          command: |
            DB_PASSWORD=$(aws secretsmanager get-secret-value \
              --secret-id aws-lecture13-ci-rds-secret \
              --query 'SecretString' \
              --output text | jq '.password')
            echo "export DB_PASSWORD=${DB_PASSWORD}" >> $BASH_ENV
      # DBホスト（RDSエンドポイント）取得 → 環境変数にセット
      - run:
          name: Get DB endpoint
          command: |
            DB_HOST=$(aws cloudformation describe-stacks \
              --stack-name raisetech-aws-lecture13-ci-application \
              --query "Stacks[0].Outputs[?OutputKey=='DBEndpoint'].OutputValue" \
              --output text)
            echo "export DB_HOST=${DB_HOST}" >> $BASH_ENV
      # ALB のDNS名を取得 → 環境変数にセット
      - run:
          name: Get ALB DNS
          command: |
            ALB_DNS=$(aws cloudformation describe-stacks \
              --stack-name raisetech-aws-lecture13-ci-application \
              --query "Stacks[0].Outputs[?OutputKey=='ALBDNS'].OutputValue" \
              --output text)
            echo "export ALB_DNS=${ALB_DNS}" >> $BASH_ENV
      # IPをworkspaceに保存（他ジョブで利用可能に）
      - persist_to_workspace:
          root: .
          paths:
            - target_ip.txt
      # AnsiblePlaybookを実行
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -i ansible/inventory

  execute_serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: 3.2.3
      - add_ssh_keys:
          fingerprints:
            - "SHA256:MfFRPirALrmTRAdw/j+bF6ghu9kvK3WI2JdrdMSSOlo"
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Check if target_ip.txt exists
          command: |
            ls -al /home/circleci/project
            cat /home/circleci/project/target_ip.txt
      - run:
          name: Setup SSH config
          command: |
            TARGET_IP=$(cat /home/circleci/project/target_ip.txt)
            echo -e "Host target\n\
            HostName ${TARGET_IP}\n\
            IdentityFile ~/.ssh/id_rsa_aws_from_m1_win.pem\n\
            User ec2-user\n\
            StrictHostKeyChecking no\n" >> ~/.ssh/config
            cat ~/.ssh/config
      - run:
          name: Install dependencies
          command: |
            cd serverspec
            bundle install
      - run:
          name: Execute Serverspec test
          command: |
            cd serverspec
            bundle exec rake spec

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  iaas-pipeline-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - cfn-lint
      - execute-cloudformation:
          requires:
            - cfn-lint
      - execute-ansible:
          requires:
            - execute-cloudformation
      - execute_serverspec:
          requires:
            - execute-ansible
